export const Accordion = () => import('../..\\components\\Accordion.vue' /* webpackChunkName: "components/accordion" */).then(c => wrapFunctional(c.default || c))
export const Alert = () => import('../..\\components\\Alert.vue' /* webpackChunkName: "components/alert" */).then(c => wrapFunctional(c.default || c))
export const BarChart = () => import('../..\\components\\BarChart.vue' /* webpackChunkName: "components/bar-chart" */).then(c => wrapFunctional(c.default || c))
export const Breadcumb = () => import('../..\\components\\Breadcumb.vue' /* webpackChunkName: "components/breadcumb" */).then(c => wrapFunctional(c.default || c))
export const ChangePassword = () => import('../..\\components\\ChangePassword.vue' /* webpackChunkName: "components/change-password" */).then(c => wrapFunctional(c.default || c))
export const Dropdown = () => import('../..\\components\\Dropdown.vue' /* webpackChunkName: "components/dropdown" */).then(c => wrapFunctional(c.default || c))
export const DropdownUpload = () => import('../..\\components\\DropdownUpload.vue' /* webpackChunkName: "components/dropdown-upload" */).then(c => wrapFunctional(c.default || c))
export const ImagesEditor = () => import('../..\\components\\ImagesEditor.vue' /* webpackChunkName: "components/images-editor" */).then(c => wrapFunctional(c.default || c))
export const KButton = () => import('../..\\components\\KButton.vue' /* webpackChunkName: "components/k-button" */).then(c => wrapFunctional(c.default || c))
export const Modal = () => import('../..\\components\\Modal.vue' /* webpackChunkName: "components/modal" */).then(c => wrapFunctional(c.default || c))
export const Navbar = () => import('../..\\components\\Navbar.vue' /* webpackChunkName: "components/navbar" */).then(c => wrapFunctional(c.default || c))
export const Pagination = () => import('../..\\components\\Pagination.vue' /* webpackChunkName: "components/pagination" */).then(c => wrapFunctional(c.default || c))
export const Popup = () => import('../..\\components\\Popup.vue' /* webpackChunkName: "components/popup" */).then(c => wrapFunctional(c.default || c))
export const Popup2 = () => import('../..\\components\\Popup2.vue' /* webpackChunkName: "components/popup2" */).then(c => wrapFunctional(c.default || c))
export const Snackbar = () => import('../..\\components\\Snackbar.vue' /* webpackChunkName: "components/snackbar" */).then(c => wrapFunctional(c.default || c))
export const SwitchOrganization = () => import('../..\\components\\SwitchOrganization.vue' /* webpackChunkName: "components/switch-organization" */).then(c => wrapFunctional(c.default || c))
export const TiptapEditor = () => import('../..\\components\\TiptapEditor.vue' /* webpackChunkName: "components/tiptap-editor" */).then(c => wrapFunctional(c.default || c))
export const Toast = () => import('../..\\components\\toast.vue' /* webpackChunkName: "components/toast" */).then(c => wrapFunctional(c.default || c))
export const ButtonBackPage = () => import('../..\\components\\button\\backPage.vue' /* webpackChunkName: "components/button-back-page" */).then(c => wrapFunctional(c.default || c))
export const ButtonDefault = () => import('../..\\components\\button\\default.vue' /* webpackChunkName: "components/button-default" */).then(c => wrapFunctional(c.default || c))
export const ButtonNext = () => import('../..\\components\\button\\next.vue' /* webpackChunkName: "components/button-next" */).then(c => wrapFunctional(c.default || c))
export const ButtonNextPage = () => import('../..\\components\\button\\nextPage.vue' /* webpackChunkName: "components/button-next-page" */).then(c => wrapFunctional(c.default || c))
export const ButtonPrev = () => import('../..\\components\\button\\prev.vue' /* webpackChunkName: "components/button-prev" */).then(c => wrapFunctional(c.default || c))
export const ButtonPrevPage = () => import('../..\\components\\button\\prevPage.vue' /* webpackChunkName: "components/button-prev-page" */).then(c => wrapFunctional(c.default || c))
export const CardCampaign = () => import('../..\\components\\card\\campaign.vue' /* webpackChunkName: "components/card-campaign" */).then(c => wrapFunctional(c.default || c))
export const CardForm = () => import('../..\\components\\card\\Form.vue' /* webpackChunkName: "components/card-form" */).then(c => wrapFunctional(c.default || c))
export const CardStatus = () => import('../..\\components\\card\\status.vue' /* webpackChunkName: "components/card-status" */).then(c => wrapFunctional(c.default || c))
export const CreativeSendSh = () => import('../..\\components\\creative\\SendSh.vue' /* webpackChunkName: "components/creative-send-sh" */).then(c => wrapFunctional(c.default || c))
export const DropdownSave = () => import('../..\\components\\dropdown\\save.vue' /* webpackChunkName: "components/dropdown-save" */).then(c => wrapFunctional(c.default || c))
export const Error = () => import('../..\\components\\error\\404.vue' /* webpackChunkName: "components/error" */).then(c => wrapFunctional(c.default || c))
export const ExpandTemplate = () => import('../..\\components\\expand\\template.vue' /* webpackChunkName: "components/expand-template" */).then(c => wrapFunctional(c.default || c))
export const FilterLayout = () => import('../..\\components\\filter\\Layout.vue' /* webpackChunkName: "components/filter-layout" */).then(c => wrapFunctional(c.default || c))
export const FilterTab = () => import('../..\\components\\filter\\Tab.vue' /* webpackChunkName: "components/filter-tab" */).then(c => wrapFunctional(c.default || c))
export const FormAudio = () => import('../..\\components\\form\\Audio.vue' /* webpackChunkName: "components/form-audio" */).then(c => wrapFunctional(c.default || c))
export const FormButton = () => import('../..\\components\\form\\Button.vue' /* webpackChunkName: "components/form-button" */).then(c => wrapFunctional(c.default || c))
export const FormColor = () => import('../..\\components\\form\\Color.vue' /* webpackChunkName: "components/form-color" */).then(c => wrapFunctional(c.default || c))
export const FormColorPallete = () => import('../..\\components\\form\\ColorPallete.vue' /* webpackChunkName: "components/form-color-pallete" */).then(c => wrapFunctional(c.default || c))
export const FormCustomSound = () => import('../..\\components\\form\\CustomSound.vue' /* webpackChunkName: "components/form-custom-sound" */).then(c => wrapFunctional(c.default || c))
export const FormImage = () => import('../..\\components\\form\\Image.vue' /* webpackChunkName: "components/form-image" */).then(c => wrapFunctional(c.default || c))
export const FormImageArray = () => import('../..\\components\\form\\ImageArray.vue' /* webpackChunkName: "components/form-image-array" */).then(c => wrapFunctional(c.default || c))
export const FormOption = () => import('../..\\components\\form\\Option.vue' /* webpackChunkName: "components/form-option" */).then(c => wrapFunctional(c.default || c))
export const FormText = () => import('../..\\components\\form\\Text.vue' /* webpackChunkName: "components/form-text" */).then(c => wrapFunctional(c.default || c))
export const FormTextColor = () => import('../..\\components\\form\\TextColor.vue' /* webpackChunkName: "components/form-text-color" */).then(c => wrapFunctional(c.default || c))
export const FormTextOnly = () => import('../..\\components\\form\\TextOnly.vue' /* webpackChunkName: "components/form-text-only" */).then(c => wrapFunctional(c.default || c))
export const IconAddUser = () => import('../..\\components\\icon\\add_user.vue' /* webpackChunkName: "components/icon-add-user" */).then(c => wrapFunctional(c.default || c))
export const IconAlertFailed = () => import('../..\\components\\icon\\alert_failed.vue' /* webpackChunkName: "components/icon-alert-failed" */).then(c => wrapFunctional(c.default || c))
export const IconAlertLoading = () => import('../..\\components\\icon\\alert_loading.vue' /* webpackChunkName: "components/icon-alert-loading" */).then(c => wrapFunctional(c.default || c))
export const IconAlertSuccess = () => import('../..\\components\\icon\\alert_success.vue' /* webpackChunkName: "components/icon-alert-success" */).then(c => wrapFunctional(c.default || c))
export const IconAll = () => import('../..\\components\\icon\\all.vue' /* webpackChunkName: "components/icon-all" */).then(c => wrapFunctional(c.default || c))
export const IconArrowDown = () => import('../..\\components\\icon\\arrow_down.vue' /* webpackChunkName: "components/icon-arrow-down" */).then(c => wrapFunctional(c.default || c))
export const IconArrowLeft = () => import('../..\\components\\icon\\arrow_left.vue' /* webpackChunkName: "components/icon-arrow-left" */).then(c => wrapFunctional(c.default || c))
export const IconArrowRight = () => import('../..\\components\\icon\\arrow_right.vue' /* webpackChunkName: "components/icon-arrow-right" */).then(c => wrapFunctional(c.default || c))
export const IconArrowRights = () => import('../..\\components\\icon\\Arrow_rights.vue' /* webpackChunkName: "components/icon-arrow-rights" */).then(c => wrapFunctional(c.default || c))
export const IconArrowUp = () => import('../..\\components\\icon\\arrow_up.vue' /* webpackChunkName: "components/icon-arrow-up" */).then(c => wrapFunctional(c.default || c))
export const IconChart = () => import('../..\\components\\icon\\chart.vue' /* webpackChunkName: "components/icon-chart" */).then(c => wrapFunctional(c.default || c))
export const IconCheck = () => import('../..\\components\\icon\\check.vue' /* webpackChunkName: "components/icon-check" */).then(c => wrapFunctional(c.default || c))
export const IconClose = () => import('../..\\components\\icon\\close.vue' /* webpackChunkName: "components/icon-close" */).then(c => wrapFunctional(c.default || c))
export const IconCompleted = () => import('../..\\components\\icon\\completed.vue' /* webpackChunkName: "components/icon-completed" */).then(c => wrapFunctional(c.default || c))
export const IconComponent = () => import('../..\\components\\icon\\component.vue' /* webpackChunkName: "components/icon-component" */).then(c => wrapFunctional(c.default || c))
export const IconCopy = () => import('../..\\components\\icon\\copy.vue' /* webpackChunkName: "components/icon-copy" */).then(c => wrapFunctional(c.default || c))
export const IconCreative = () => import('../..\\components\\icon\\creative.vue' /* webpackChunkName: "components/icon-creative" */).then(c => wrapFunctional(c.default || c))
export const IconCrop = () => import('../..\\components\\icon\\crop.vue' /* webpackChunkName: "components/icon-crop" */).then(c => wrapFunctional(c.default || c))
export const IconCustomSound = () => import('../..\\components\\icon\\custom_sound.vue' /* webpackChunkName: "components/icon-custom-sound" */).then(c => wrapFunctional(c.default || c))
export const IconDelete = () => import('../..\\components\\icon\\delete.vue' /* webpackChunkName: "components/icon-delete" */).then(c => wrapFunctional(c.default || c))
export const IconDollar = () => import('../..\\components\\icon\\dollar.vue' /* webpackChunkName: "components/icon-dollar" */).then(c => wrapFunctional(c.default || c))
export const IconDrag = () => import('../..\\components\\icon\\drag.vue' /* webpackChunkName: "components/icon-drag" */).then(c => wrapFunctional(c.default || c))
export const IconEdit = () => import('../..\\components\\icon\\edit.vue' /* webpackChunkName: "components/icon-edit" */).then(c => wrapFunctional(c.default || c))
export const IconEyes = () => import('../..\\components\\icon\\eyes.vue' /* webpackChunkName: "components/icon-eyes" */).then(c => wrapFunctional(c.default || c))
export const IconFilter = () => import('../..\\components\\icon\\filter.vue' /* webpackChunkName: "components/icon-filter" */).then(c => wrapFunctional(c.default || c))
export const IconFormButton = () => import('../..\\components\\icon\\form_button.vue' /* webpackChunkName: "components/icon-form-button" */).then(c => wrapFunctional(c.default || c))
export const IconFormColor = () => import('../..\\components\\icon\\form_color.vue' /* webpackChunkName: "components/icon-form-color" */).then(c => wrapFunctional(c.default || c))
export const IconFormImage = () => import('../..\\components\\icon\\form_image.vue' /* webpackChunkName: "components/icon-form-image" */).then(c => wrapFunctional(c.default || c))
export const IconFormText = () => import('../..\\components\\icon\\form_text.vue' /* webpackChunkName: "components/icon-form-text" */).then(c => wrapFunctional(c.default || c))
export const IconHastagh = () => import('../..\\components\\icon\\hastagh.vue' /* webpackChunkName: "components/icon-hastagh" */).then(c => wrapFunctional(c.default || c))
export const IconHidePanel = () => import('../..\\components\\icon\\hide_panel.vue' /* webpackChunkName: "components/icon-hide-panel" */).then(c => wrapFunctional(c.default || c))
export const IconHidePassword = () => import('../..\\components\\icon\\hide_password.vue' /* webpackChunkName: "components/icon-hide-password" */).then(c => wrapFunctional(c.default || c))
export const IconInactive = () => import('../..\\components\\icon\\inactive.vue' /* webpackChunkName: "components/icon-inactive" */).then(c => wrapFunctional(c.default || c))
export const IconInfo = () => import('../..\\components\\icon\\info.vue' /* webpackChunkName: "components/icon-info" */).then(c => wrapFunctional(c.default || c))
export const IconLeft = () => import('../..\\components\\icon\\left.vue' /* webpackChunkName: "components/icon-left" */).then(c => wrapFunctional(c.default || c))
export const IconLineChart = () => import('../..\\components\\icon\\line_chart.vue' /* webpackChunkName: "components/icon-line-chart" */).then(c => wrapFunctional(c.default || c))
export const IconList = () => import('../..\\components\\icon\\list.vue' /* webpackChunkName: "components/icon-list" */).then(c => wrapFunctional(c.default || c))
export const IconLock = () => import('../..\\components\\icon\\lock.vue' /* webpackChunkName: "components/icon-lock" */).then(c => wrapFunctional(c.default || c))
export const IconLogout = () => import('../..\\components\\icon\\logout.vue' /* webpackChunkName: "components/icon-logout" */).then(c => wrapFunctional(c.default || c))
export const IconMenuAdmin = () => import('../..\\components\\icon\\menu_admin.vue' /* webpackChunkName: "components/icon-menu-admin" */).then(c => wrapFunctional(c.default || c))
export const IconMenuAudience = () => import('../..\\components\\icon\\menu_audience.vue' /* webpackChunkName: "components/icon-menu-audience" */).then(c => wrapFunctional(c.default || c))
export const IconMenuCampaign = () => import('../..\\components\\icon\\menu_campaign.vue' /* webpackChunkName: "components/icon-menu-campaign" */).then(c => wrapFunctional(c.default || c))
export const IconMenuCreative = () => import('../..\\components\\icon\\menu_creative.vue' /* webpackChunkName: "components/icon-menu-creative" */).then(c => wrapFunctional(c.default || c))
export const IconMenuDashboard = () => import('../..\\components\\icon\\menu_dashboard.vue' /* webpackChunkName: "components/icon-menu-dashboard" */).then(c => wrapFunctional(c.default || c))
export const IconMenuReport = () => import('../..\\components\\icon\\menu_report.vue' /* webpackChunkName: "components/icon-menu-report" */).then(c => wrapFunctional(c.default || c))
export const IconMenuSurvey = () => import('../..\\components\\icon\\menu_survey.vue' /* webpackChunkName: "components/icon-menu-survey" */).then(c => wrapFunctional(c.default || c))
export const IconMenuTemplate = () => import('../..\\components\\icon\\menu_template.vue' /* webpackChunkName: "components/icon-menu-template" */).then(c => wrapFunctional(c.default || c))
export const IconMenuTools = () => import('../..\\components\\icon\\menu_tools.vue' /* webpackChunkName: "components/icon-menu-tools" */).then(c => wrapFunctional(c.default || c))
export const IconMenuUser = () => import('../..\\components\\icon\\menu_user.vue' /* webpackChunkName: "components/icon-menu-user" */).then(c => wrapFunctional(c.default || c))
export const IconMinus = () => import('../..\\components\\icon\\minus.vue' /* webpackChunkName: "components/icon-minus" */).then(c => wrapFunctional(c.default || c))
export const IconNext = () => import('../..\\components\\icon\\next.vue' /* webpackChunkName: "components/icon-next" */).then(c => wrapFunctional(c.default || c))
export const IconNotification = () => import('../..\\components\\icon\\notification.vue' /* webpackChunkName: "components/icon-notification" */).then(c => wrapFunctional(c.default || c))
export const IconOrganization = () => import('../..\\components\\icon\\organization.vue' /* webpackChunkName: "components/icon-organization" */).then(c => wrapFunctional(c.default || c))
export const IconPassword = () => import('../..\\components\\icon\\password.vue' /* webpackChunkName: "components/icon-password" */).then(c => wrapFunctional(c.default || c))
export const IconPause = () => import('../..\\components\\icon\\pause.vue' /* webpackChunkName: "components/icon-pause" */).then(c => wrapFunctional(c.default || c))
export const IconPauseV2 = () => import('../..\\components\\icon\\pause_v2.vue' /* webpackChunkName: "components/icon-pause-v2" */).then(c => wrapFunctional(c.default || c))
export const IconPlay = () => import('../..\\components\\icon\\play.vue' /* webpackChunkName: "components/icon-play" */).then(c => wrapFunctional(c.default || c))
export const IconPlayV2 = () => import('../..\\components\\icon\\play_v2.vue' /* webpackChunkName: "components/icon-play-v2" */).then(c => wrapFunctional(c.default || c))
export const IconPlus = () => import('../..\\components\\icon\\plus.vue' /* webpackChunkName: "components/icon-plus" */).then(c => wrapFunctional(c.default || c))
export const IconPrev = () => import('../..\\components\\icon\\prev.vue' /* webpackChunkName: "components/icon-prev" */).then(c => wrapFunctional(c.default || c))
export const IconPriceDown = () => import('../..\\components\\icon\\price_down.vue' /* webpackChunkName: "components/icon-price-down" */).then(c => wrapFunctional(c.default || c))
export const IconPriceUp = () => import('../..\\components\\icon\\price_up.vue' /* webpackChunkName: "components/icon-price-up" */).then(c => wrapFunctional(c.default || c))
export const IconProfile = () => import('../..\\components\\icon\\profile.vue' /* webpackChunkName: "components/icon-profile" */).then(c => wrapFunctional(c.default || c))
export const IconRefresh = () => import('../..\\components\\icon\\refresh.vue' /* webpackChunkName: "components/icon-refresh" */).then(c => wrapFunctional(c.default || c))
export const IconReload = () => import('../..\\components\\icon\\reload.vue' /* webpackChunkName: "components/icon-reload" */).then(c => wrapFunctional(c.default || c))
export const IconRight = () => import('../..\\components\\icon\\right.vue' /* webpackChunkName: "components/icon-right" */).then(c => wrapFunctional(c.default || c))
export const IconRunning = () => import('../..\\components\\icon\\running.vue' /* webpackChunkName: "components/icon-running" */).then(c => wrapFunctional(c.default || c))
export const IconSave = () => import('../..\\components\\icon\\save.vue' /* webpackChunkName: "components/icon-save" */).then(c => wrapFunctional(c.default || c))
export const IconSearch = () => import('../..\\components\\icon\\search.vue' /* webpackChunkName: "components/icon-search" */).then(c => wrapFunctional(c.default || c))
export const IconSend = () => import('../..\\components\\icon\\send.vue' /* webpackChunkName: "components/icon-send" */).then(c => wrapFunctional(c.default || c))
export const IconSetting = () => import('../..\\components\\icon\\setting.vue' /* webpackChunkName: "components/icon-setting" */).then(c => wrapFunctional(c.default || c))
export const IconShowPanel = () => import('../..\\components\\icon\\show_panel.vue' /* webpackChunkName: "components/icon-show-panel" */).then(c => wrapFunctional(c.default || c))
export const IconShowPassword = () => import('../..\\components\\icon\\show_password.vue' /* webpackChunkName: "components/icon-show-password" */).then(c => wrapFunctional(c.default || c))
export const IconStop = () => import('../..\\components\\icon\\stop.vue' /* webpackChunkName: "components/icon-stop" */).then(c => wrapFunctional(c.default || c))
export const IconTextBold = () => import('../..\\components\\icon\\text_bold.vue' /* webpackChunkName: "components/icon-text-bold" */).then(c => wrapFunctional(c.default || c))
export const IconTextCenter = () => import('../..\\components\\icon\\text_center.vue' /* webpackChunkName: "components/icon-text-center" */).then(c => wrapFunctional(c.default || c))
export const IconTextItalic = () => import('../..\\components\\icon\\text_italic.vue' /* webpackChunkName: "components/icon-text-italic" */).then(c => wrapFunctional(c.default || c))
export const IconTextJustify = () => import('../..\\components\\icon\\text_justify.vue' /* webpackChunkName: "components/icon-text-justify" */).then(c => wrapFunctional(c.default || c))
export const IconTextLeft = () => import('../..\\components\\icon\\text_left.vue' /* webpackChunkName: "components/icon-text-left" */).then(c => wrapFunctional(c.default || c))
export const IconTextRight = () => import('../..\\components\\icon\\text_right.vue' /* webpackChunkName: "components/icon-text-right" */).then(c => wrapFunctional(c.default || c))
export const IconTextStrike = () => import('../..\\components\\icon\\text_strike.vue' /* webpackChunkName: "components/icon-text-strike" */).then(c => wrapFunctional(c.default || c))
export const IconTextUnderlined = () => import('../..\\components\\icon\\text_underlined.vue' /* webpackChunkName: "components/icon-text-underlined" */).then(c => wrapFunctional(c.default || c))
export const IconUpload = () => import('../..\\components\\icon\\upload.vue' /* webpackChunkName: "components/icon-upload" */).then(c => wrapFunctional(c.default || c))
export const IconUser = () => import('../..\\components\\icon\\user.vue' /* webpackChunkName: "components/icon-user" */).then(c => wrapFunctional(c.default || c))
export const IconUserSetting = () => import('../..\\components\\icon\\user_setting.vue' /* webpackChunkName: "components/icon-user-setting" */).then(c => wrapFunctional(c.default || c))
export const IconView = () => import('../..\\components\\icon\\view.vue' /* webpackChunkName: "components/icon-view" */).then(c => wrapFunctional(c.default || c))
export const ProgressBar = () => import('../..\\components\\progress\\bar.vue' /* webpackChunkName: "components/progress-bar" */).then(c => wrapFunctional(c.default || c))
export const Sidebar = () => import('../..\\components\\sidebar\\index.vue' /* webpackChunkName: "components/sidebar" */).then(c => wrapFunctional(c.default || c))
export const SidebarItemList = () => import('../..\\components\\sidebar\\ItemList.vue' /* webpackChunkName: "components/sidebar-item-list" */).then(c => wrapFunctional(c.default || c))
export const UserChangePassword = () => import('../..\\components\\user\\ChangePassword.vue' /* webpackChunkName: "components/user-change-password" */).then(c => wrapFunctional(c.default || c))
export const UserCreate = () => import('../..\\components\\user\\Create.vue' /* webpackChunkName: "components/user-create" */).then(c => wrapFunctional(c.default || c))
export const UserCreateOrganization = () => import('../..\\components\\user\\CreateOrganization.vue' /* webpackChunkName: "components/user-create-organization" */).then(c => wrapFunctional(c.default || c))
export const FormEditAudio = () => import('../..\\components\\form\\edit\\Audio.vue' /* webpackChunkName: "components/form-edit-audio" */).then(c => wrapFunctional(c.default || c))
export const FormEditButton = () => import('../..\\components\\form\\edit\\Button.vue' /* webpackChunkName: "components/form-edit-button" */).then(c => wrapFunctional(c.default || c))
export const FormEditColor = () => import('../..\\components\\form\\edit\\Color.vue' /* webpackChunkName: "components/form-edit-color" */).then(c => wrapFunctional(c.default || c))
export const FormEditColorPallete = () => import('../..\\components\\form\\edit\\ColorPallete.vue' /* webpackChunkName: "components/form-edit-color-pallete" */).then(c => wrapFunctional(c.default || c))
export const FormEditCustomSound = () => import('../..\\components\\form\\edit\\CustomSound.vue' /* webpackChunkName: "components/form-edit-custom-sound" */).then(c => wrapFunctional(c.default || c))
export const FormEditImage = () => import('../..\\components\\form\\edit\\Image.vue' /* webpackChunkName: "components/form-edit-image" */).then(c => wrapFunctional(c.default || c))
export const FormEditImageArray = () => import('../..\\components\\form\\edit\\ImageArray.vue' /* webpackChunkName: "components/form-edit-image-array" */).then(c => wrapFunctional(c.default || c))
export const FormEditOption = () => import('../..\\components\\form\\edit\\Option.vue' /* webpackChunkName: "components/form-edit-option" */).then(c => wrapFunctional(c.default || c))
export const FormEditText = () => import('../..\\components\\form\\edit\\Text.vue' /* webpackChunkName: "components/form-edit-text" */).then(c => wrapFunctional(c.default || c))
export const FormEditTextColor = () => import('../..\\components\\form\\edit\\TextColor.vue' /* webpackChunkName: "components/form-edit-text-color" */).then(c => wrapFunctional(c.default || c))
export const FormEditTextOnly = () => import('../..\\components\\form\\edit\\TextOnly.vue' /* webpackChunkName: "components/form-edit-text-only" */).then(c => wrapFunctional(c.default || c))

// nuxt/nuxt.js#8607
function wrapFunctional(options) {
  if (!options || !options.functional) {
    return options
  }

  const propKeys = Array.isArray(options.props) ? options.props : Object.keys(options.props || {})

  return {
    render(h) {
      const attrs = {}
      const props = {}

      for (const key in this.$attrs) {
        if (propKeys.includes(key)) {
          props[key] = this.$attrs[key]
        } else {
          attrs[key] = this.$attrs[key]
        }
      }

      return h(options, {
        on: this.$listeners,
        attrs,
        props,
        scopedSlots: this.$scopedSlots,
      }, this.$slots.default)
    }
  }
}
