server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /usr/share/nginx/html;
    index index.html index.htm;

    server_name _;

    location / {
        # autoindex on;
        # autoindex_exact_size on;

        if ($http_origin = '') {
            set $http_origin "*";
        }

        proxy_hide_header Access-Control-Allow-Origin;
        add_header Access-Control-Allow-Origin $http_origin;
        # try_files $uri $uri/ =404;
    }
}
